spring:
  application:
    name: StudentServ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/collegeattendance
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
server:
  port: 2000
  